# .github/workflows/auto-format.yml
name: Format Markdown

on:
  push:
    paths:
      - '**/*.md'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          args: "**/*.md"