name: Format Markdown

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          args: '**/*.md'
