title: "学習ログ"
description: "毎日のGit/GitHub学習記録"
baseurl: "/daily-commit-log"
url: "https://syokota-cyber.github.io"

# テーマ設定
theme: minima

# プラグイン設定
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-remote-theme

# ビルド設定
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - markdown: kramdown
  - kramdown:
      input: GFM
      hard_wrap: false

# サイト設定
locale: "ja-JP"
timezone: "Asia/Tokyo"
paginate: 5
paginate_path: "/page:num/"

# 投稿設定
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# 投稿の並び順
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
    sort_by: date
    reverse: true