<<<<<<< HEAD
name: Deploy GitHub Pages
=======
name: Disable GitHub Pages
>>>>>>> ba02d60 (Remove Jekyll files and disable GitHub Pages)

on:
  push:
    branches: [ main ]
<<<<<<< HEAD
    paths:
      - 'docs/**'
      - '.github/workflows/pages.yml'
=======
>>>>>>> ba02d60 (Remove Jekyll files and disable GitHub Pages)
  workflow_dispatch:

permissions:
  contents: write

jobs:
<<<<<<< HEAD
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs 
=======
  disable-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Disable GitHub Pages
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pages \
            -d '{"source":{"branch":"none"}}' 
>>>>>>> ba02d60 (Remove Jekyll files and disable GitHub Pages)
